### ISSUE TITLE
Feature: Utility for combining GPS logs and air quality CSV files

### ISSUE THREAD

**Issue by smcclellan7** [openoakland/woaq#3]
We have some citizen science air quality data that is fresh off the devices. The challenge is that it gets exported as two separate files, one GPS file, one csv with the actual air quality recording. They need to be joined together into csvs following the format of the data we pulled from MySQL.

Example GPS file: 
[GPS_20140717_193858_8530C.log](https://github.com/openoakland/woaq/files/1854528/GPS_20140717_193858_8530C.log)

Example AQ CSV (converted to .xlsx because github doesn't support .csv):
[8530C_2-5_002.xlsx](https://github.com/openoakland/woaq/files/1854533/8530C_2-5_002.xlsx)

**Comment by tdooner** [comment]
I'd love to hook you all up with access to CARTO, a cloud product that allows for easy storage and visualization of spatial data. Let me know if you'd like it.

**Comment by smcclellan7** [comment]
Alright the PR is pretty much set to go: https://github.com/openoakland/woaq/pull/4/files

My only big question is what form the output should be in. Quoting from the task list document:

> They need to be joined together into csvs following the format of the data we pulled from MySQL

I don't know what csvs this is referring to. Does someone have an example of one?

**Comment by Ethan-bradley** [comment]
This project is done, it is now part of the Heroku Upload data upload app.

**Comment by theecrit** [comment]
@Ethan-bradley @kuanb I'd like to follow-up on @kuanb's question from several months ago. I'm having trouble following how the original data files have been processed (or the thinking behind the decisions). This makes it difficult for later team members to know if the data currently in the Data Catalog is accurate, manipulated, or what (and how).  

@smcclellan7 I realize it's been a while, but can you help us understand exactly what was done here? 
@Ethan-bradley Maybe you can weigh in, since you've been working with the joiner script more recently (I think)?

Thanks!

**Comment by smcclellan7** [comment]
@theecrit @kuanb yeah, I've been AWOL for a while, sorry, but I can try to help. (I would recommend taking anything I say with a grain of salt, though. I had zero knowledge about GPS logs, or any of this stuff, going into this.) If the question is "how did I parse the NMEA sentences," I didn't do it myself, I used a library, pynmea2:

line 141: `gps = pynmea2.parse(self._gps_data.next().strip())`

I just assumed that that library would extract the long/lat correctly. But I could be missing something.

**Comment by theecrit** [comment]
@smcclellan7 Thank you!
